- name: Set system-wide proxy permanently
  hosts: private, internal
  become: true
  vars:
    proxy_ip: "192.168.1.6" # <--- ใส่ IP ของ Squid Proxy ที่นี่

  tasks:
    - name: Create proxy configuration file
      ansible.builtin.copy:
        dest: /etc/profile.d/proxy.sh
        content: |
          #!/bin/sh
          export http_proxy="http://{{ proxy_ip }}:3128"
          export https_proxy="http://{{ proxy_ip }}:3128"
          export no_proxy="localhost,127.0.0.1,*.internal.domain"
        mode: '0644'

