- name: Configure Docker APT Repository and Install Docker on Ubuntu
  hosts: jenkins # <--- เปลี่ยนเป็นชื่อกลุ่มเซิร์ฟเวอร์ Ubuntu ของคุณใน inventory
  become: yes # <--- รันด้วยสิทธิ์ root (sudo)

  tasks:
    - name: Ensure apt cache is updated (initial update)
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisite packages for Docker repository
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create directory for APT keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to APT sources
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache again after adding new repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes # อัปเดต cache อีกครั้งก่อนติดตั้ง เพื่อให้แน่ใจว่าได้ข้อมูลแพ็กเกจล่าสุดจาก Docker repo