---
- import_playbook: Configure-HTTP-HTTPS-proxy.yaml
- import_playbook: Deploy-config-Squidproxy.yaml
- import_playbook: Deploy-config-Haproxy.yaml
- import_playbook: Deploy-jenkins.yaml
- import_playbook: Deploy-k8s.yaml