- name: Install SquidProxy
  apt:
    name: squid
    state: present
    update_cache: yes

- name: Insert Squid ACL config into squid.conf
  blockinfile:
    path: /etc/squid/squid.conf
    marker: "# {mark} ANSIBLE_MANAGED_SQUID_ACL"
    block: |
      acl private_network src {{ private_cidr }}
      acl internal_network src {{ internal_cidr }}

      http_access allow private_network
      http_access allow internal_network

  notify: Restart Squid

- name: Enable and start SquidProxy
  systemd:
    name: squid
    enabled: true
    state: started
